### ISSUE TITLE
Bump to 4.24.1 breaks build

### ISSUE THREAD

**Issue by rebelchris** [fastify/fastify#5094]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.24.1

### Node.js version

18.16

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

14.0

### Description

If I bump from 4.23.2 to 4.24.1 I get following build error.
Not 100% sure if it's related, but seems to be the stuff introduced [here](https://github.com/fastify/fastify/pull/5082).

Error I get:

```
node_modules/fastify/types/instance.d.ts:146:3 - error TS1169: A computed property name in an interface must refer to an expression whose type is a literal type or a 'unique symbol' type.

146   [Symbol.asyncDispose](): Promise<undefined>;
      ~~~~~~~~~~~~~~~~~~~~~

node_modules/fastify/types/instance.d.ts:146:11 - error TS2339: Property 'asyncDispose' does not exist on type 'SymbolConstructor'.

146   [Symbol.asyncDispose](): Promise<undefined>;
              ~~~~~~~~~~~~

Found 2 errors in the same file, starting at: node_modules/fastify/types/instance.d.ts:146
```

Wondering if anyone can shed some light on it, or advise.

### Steps to Reproduce

I don't have bare minimal reproduction, but you can see the fail from bump [here](https://github.com/dailydotdev/daily-api/pull/1475).

**Comment by Uzlopak** [comment]
asyncDispose was introduced with #5082 by @arthurfiorette 

If I remember correctly Symbol.asyncDispose was added to the node typings last week or so, by uncommenting the already existing comments. Dont know if it is released already.

Maybe by using latest nodejs v20 typings it will not throw typescript errors. Dont know if asyncDispose is available for node v18, or if the typings were backported to v18.

We could try to fix the typings by adding a ts-ignore above asyncDispose.

But I wonder... What if e.g. node 14 does not have asyncDispose. Does this mean that fastify instances have a potential `undefined` attribute, when Symbol.asyncDispose is not found?

**Comment by Uzlopak** [comment]
Oh wait. Merged 3 hours ago

https://github.com/nodejs/node/pull/50123

It needs typescript 5.2?

**Comment by arthurfiorette** [comment]
It probably only breaks with `skipLibCheck: false`. We could re-ship it with a `//@ts-ignore` comment or we could extend the global Symbol namespace ourselves.

**Comment by arthurfiorette** [comment]
@rebelchris are you using nodejs 18, right? This error only appears if `@types/node` package is installed with a version below 17. Try updating your `@types/node` version to 18+ or diasble `skipLibCheck` inside your tsconfig.

**Comment by rebelchris** [comment]
@arthurfiorette my nodes/rypes are set to 18.16.17

**Comment by arthurfiorette** [comment]
And what typescript version?

**Comment by rebelchris** [comment]
Typescript 5.2.2

**Comment by mcollina** [comment]
released v4.24.2

**Comment by rebelchris** [comment]
Thanks everyone for the swift actions.
Just wanted to inform you on 4.24.2 it does work 🙏
