### PR TITLE
chore: add support for TypeScript 4.8

### LINKED ISSUE #4221: Does not work with TypeScript 4.8
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.5.2

### Plugin version

_No response_

### Node.js version

16.17.0

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

12.15.1

### Description

The fresh TypeScript 4.8 release is not compatible with Fastify's types.

Example:

```
node_modules/fastify/types/route.d.ts:48:98 - error TS2344: Type 'SchemaCompiler' does not satisfy the constraint 'FastifySchema'.

48   onRequest?: onRequestHookHandler<RawServer, RawRequest, RawReply, RouteGeneric, ContextConfig, SchemaCompiler, TypeProvider, Logger> | onRequestHookHandler<RawServer, RawRequest, RawReply, RouteGeneric, ContextConfig,
SchemaCompiler, TypeProvider, Logger>[];
                                                                                                    ~~~~~~~~~~~~~~

  node_modules/fastify/types/route.d.ts:27:3
    27   SchemaCompiler = FastifySchema,
         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    This type parameter might need an `extends FastifySchema` constraint.
```

/cc @fastify/typescript 

### Steps to Reproduce

See https://github.com/SimenB/fastify-ts

### Expected Behavior

No type error

### PR DESCRIPTION
**Pull request by SimenB**
#### Checklist

- [ ] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

Fixes #4221

The error says "This type parameter might need an `extends FastifySchema` constraint.", so I added them.

### CODE REVIEW

**Review by mcollina — APPROVED** [review]
lgtm
