### ISSUE TITLE
PrettyPrint for logger doesn't work in v3 [TypeScript]

### ISSUE THREAD

**Issue by lludol** [fastify/fastify#2388]
## 💥 Regression Report

The logger doesn't accept anymore the prettyPrint option with TypeScript.

## Last working version

Worked up to version: 2.8.0

Stopped working in version: 3.0.0

## To Reproduce

```js
const app = fastify({
	logger: {
		prettyPrint: true,
	},
});
```
```shell
src/index.ts:99:4 - error TS2769: No overload matches this call.
  The last overload gave the following error.
    Type '{ prettyPrint: boolean; }' is not assignable to type 'boolean | FastifyLoggerInstance | FastifyLoggerOptions<Server, IncomingMessage, ServerResponse> | undefined'.
      Object literal may only specify known properties, and 'prettyPrint' does not exist in type 'FastifyLoggerInstance | FastifyLoggerOptions<Server, IncomingMessage, ServerResponse>'.

99              prettyPrint: true,
                ~~~~~~~~~~~~~~~~~

  node_modules/fastify/fastify.d.ts:41:18
    41 declare function fastify<
                        ~~~~~~~
    The last overload is declared here.


Found 1 error.

error Command failed with exit code 2.
```

## Expected behavior

A pretty logger and not this json log: 
```shell
{"level":30,"time":1594224182021,"pid":22089,"hostname":"DESKTOP-SGN7MGS","reqId":3,"res":{"statusCode":200},"responseTime":2143.8535000011325,"msg":"request completed"}
```

## Your Environment

- *node version*: 12
- *fastify version*: 3.0.0
- *os*: Ubuntu bash (Windows 10)

**Comment by Eomm** [comment]
Does [this guide](https://github.com/fastify/fastify/blob/2f56e10a24ecb70c2c7950bfffd60eda8f7782a6/docs/TypeScript.md#example-5-specifying-logger-types) work for you?

I found a comment in the source:

https://github.com/fastify/fastify/blob/3ac821266171afbf0f290c64610d78009a948484/types/logger.d.ts#L34-L36

**Comment by lludol** [comment]
@Eomm Thank you!! 😍

Now it works!

````javascript
const app = fastify<http.Server, http.IncomingMessage, http.ServerResponse, pino.Logger>({
	logger: {
		prettyPrint: true,
	},
});
```

**Comment by Ethan-Arrowood** [comment]
This could use better documentation. Maybe a section under the logger page and even the server page under the logger option. Would you be interested in contributing?

**Comment by mcollina** [comment]
I think we can include the `prettyPrint` option as well, it’s very common!

**Comment by Ethan-Arrowood** [comment]
Creating an issue for this documentation improvement. @lludol you get first dibs on it if you'd like; otherwise I'll mark it as good-first-issue and let someone else go for it. Please let us know promptly if you'd like to work on it :smile:

**Comment by lludol** [comment]
@Ethan-Arrowood it's okay, we can close this one and continue on the new one.
