### ISSUE TITLE
A change in Fastify hook types broke our hooks

### ISSUE THREAD

**Issue by anttti** [fastify/fastify#3620]
## 💬  A change in Fastify hook types broke our hooks

When upgrading Fastify we encountered strange problems with our `preHandler`-hooks. Narrowing down, the problem was introduced when upgrading from 3.18.0 to 3.18.1, and more specifically it was this change: https://github.com/fastify/fastify/pull/3143/files

Given a custom hook
```ts
// A hook that does nothing, just to demonstrate the issue with the types
const myHook: preHandlerAsyncHookHandler<
  RawServerBase,
  RawRequestDefaultExpression<RawServerBase>,
  RawReplyDefaultExpression<RawServerBase>,
  {}
> = async (_req, _res) => undefined;
```

and using it like this
```ts
interface TestRoute extends RouteGenericInterface {
  readonly Reply: { ok: boolean };
}

const testRoutes: FastifyPluginAsync = (instance) => {
  instance.addHook("preHandler", myHook);

  instance.route<TestRoute>({
    method: "GET",
    url: "/",
    handler: async (_req, res) => res.send({ ok: true }),
  });

  return Promise.resolve();
};
```

we get this error
```
src/testRoutes.ts:27:20 - error TS2769: No overload matches this call.
  The last overload gave the following error.
    Argument of type '"preHandler"' is not assignable to parameter of type '"onClose"'.

27   instance.addHook("preHandler", myHook);
                      ~~~~~~~~~~~~

  node_modules/fastify/types/instance.d.ts:307:3
    307   addHook(
          ~~~~~~~~
    308     name: 'onClose',
        ~~~~~~~~~~~~~~~~~~~~
    309     hook: onCloseHookHandler<RawServer, RawRequest, RawReply, Logger>
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    310   ): FastifyInstance<RawServer, RawRequest, RawReply, Logger>;
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    The last overload is declared here.
```

I set up a minimal project demonstrating just this issue: https://github.com/anttti/fastify-types

Just run `yarn && yarn build` to see the error. 

What are we doing wrong?

## Your Environment

- *node version*: 14.15.4
- *fastify version*: 3.18.1 and onwards
- *os*: Mac, but issue seems to be platform independent

**Comment by mcollina** [comment]
@darkgl0w can you open a fix?

Also @siberex  wdyt?

**Comment by darkgl0w** [comment]
@mcollina > I am on my way to home, I will take a look as soon as possible.

But I have the feeling that updating all the changes that were made to the file `hooks.d.ts` in the aforementioned PR with something like this will do the trick to type `this` :

```ts
/**
 * `preHandler` is the fourth hook to be executed in the request lifecycle. The previous hook was `preValidation`, the next hook will be `preSerialization`.
 */
export interface preHandlerHookHandler<
  RawServer extends RawServerBase = RawServerDefault,
  RawRequest extends RawRequestDefaultExpression<RawServer> = RawRequestDefaultExpression<RawServer>,
  RawReply extends RawReplyDefaultExpression<RawServer> = RawReplyDefaultExpression<RawServer>,
  RouteGeneric extends RouteGenericInterface = RouteGenericInterface,
  ContextConfig = ContextConfigDefault
> {
  (
    // change: this: FastifyInstance<RawServer, RawRequest, RawReply>,
    // to :
    this: FastifyInstance,
    request: FastifyRequest<RouteGeneric, RawServer, RawRequest>,
    reply: FastifyReply<RawServer, RawRequest, RawReply, RouteGeneric, ContextConfig>,
    done: HookHandlerDoneFunction
  ): void;
}
```
WDYT @fastify/typescript ? is it valid ?

PS: I am on my phone, sorry if there are typos/spelling errors or copy/paste issues :d

**Comment by siberex** [comment]
Yeah, you absolutely right, @darkgl0w. I will land PR right in a moment...

**Comment by darkgl0w** [comment]
@siberex > it's ok I could make the changes from my phone thanks to `github.dev` vscode ^^

**Comment by anttti** [comment]
Thank you for such a quick response! ❤️

**Comment by fox1t** [comment]
I am not sure that this PR was a good one. :/

The issue was that `RawServerBase` is a union type. We should allow only passing one type as `RawServer`, the one that the user chooses to use. `RawServerBase` restricts the possible choices and should not be used as Generic. @anttti, you should use `RawServerDefault` as the first parameter of your definition, and we shouldn't remove that generics from https://github.com/fastify/fastify/blob/main/types/hooks.d.ts#L165

Please check this PR for more insights: https://github.com/fastify/fastify/pull/3785
