### ISSUE TITLE
Build error in v4.14.1 importing non-existant `SerializerFactory`

### ISSUE THREAD

**Issue by ChrisCrewdson** [fastify/fastify#4615]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

v4.14.1

### Node.js version

16.19.1

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

20.04

### Description

The export `SerializerFactory` that is imported does not exist in `@fastify/fast-json-stringify-compiler`. This used to import `SerializerCompiler` which does exist.

Here is the compilation error:
```
node_modules/fastify/fastify.d.ts:8:33 - error TS2614: Module '"@fastify/fast-json-stringify-compiler"' has no exported member 'SerializerFactory'. Did you mean to use 'import SerializerFactory from "@fastify/fast-json-stringify-compiler"' instead?

8 import { Options as FJSOptions, SerializerFactory } from '@fastify/fast-json-stringify-compiler'
                                  ~~~~~~~~~~~~~~~~~

node_modules/fastify/types/schema.d.ts:2:10 - error TS2614: Module '"@fastify/fast-json-stringify-compiler"' has no exported member 'SerializerFactory'. Did you mean to use 'import SerializerFactory from "@fastify/fast-json-stringify-compiler"' instead?

2 import { SerializerFactory } from '@fastify/fast-json-stringify-compiler'
```

### Steps to Reproduce

Use `tsc` to build with `fastify@4.14.1`

### Expected Behavior

Build completes with no errors.

**Comment by Uzlopak** [comment]
Run `npm update`.

**Comment by ChrisCrewdson** [comment]
I don't fully understand why this worked, but it did. Thank you.
