### ISSUE TITLE
Bump dependency version of `pino` to `^6.13.2`

### ISSUE THREAD

**Issue by RaenonX** [fastify/fastify#3305]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

3.21.0

### Node.js version

14.17.0

### Operating system

Windows

### Operating system version (i.e. 20.04, 11.3, 10)

10

### Description

I found that the required `pino` version of `fastify` in my `package-lock.json` is `^6.13.0`. However, this version of `pino` with `pino-pretty@7.0.0` when `prettyPrint` config option is enabled causes the error: `pretty is not a function`.

I have checked #3101, but that is waiting for `pino@7` instead so I don't think it's related to this.

This occurs when I bumped `pino-pretty` to v7 of an existing application.

------------------

Stacktrace:

```
const formatted = pretty(typeof redact === 'function' ? redact(obj) : obj)
                  ^
TypeError: pretty is not a function
    at Object.write (D:\UserData\Downloads\untitled\node_modules\pino\lib\tools.js:282:25)
    at Pino.write (D:\UserData\Downloads\untitled\node_modules\pino\lib\proto.js:212:15)
    at Pino.LOG [as info] (D:\UserData\Downloads\untitled\node_modules\pino\lib\tools.js:57:21)
    at logServerAddress (D:\UserData\Downloads\untitled\node_modules\fastify\lib\server.js:132:16)
    at Server.wrap (D:\UserData\Downloads\untitled\node_modules\fastify\lib\server.js:79:25)
    at Object.onceWrapper (events.js:482:28)
    at Server.emit (events.js:376:20)
    at emitListeningNT (net.js:1352:10)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)
```

### Steps to Reproduce

Have these dependencies in `package.json` then run `npm install`:

```
"dependencies": {
  "fastify": "^3.21.0",
  "pino": "6.13.0"
},
"devDependencies": {
  "pino-pretty": "^7.0.0"
},
```

> If `pino` has to be specified, otherwise `npm` automatically installs `6.13.2` which fixes this problem.

Then, run this js file:

```js
const fastify = require('fastify')({
  logger: {prettyPrint: {translateTime: true}}
})

// Declare a route
fastify.get('/', function (request, reply) {
  reply.send({ hello: 'world' })
})

// Run the server!
fastify.listen(9999, function (err, address) {
  if (err) {
    fastify.log.error(err)
    process.exit(1)
  }
  // Server is now listening on ${address}
})
```

> Copied from getting started with `logger.prettyPrint` option specified.

### Expected Behavior

No error should occur.

**Comment by climba03003** [comment]
I can only see you are using an exact version for `pino` and which is not related to `fastify`.

**Comment by RaenonX** [comment]
> I can only see you are using an exact version for `pino` and which is not related to `fastify`.
> 
> My advice would be reinstall the dependency. As `^6.13.0` will actually install `6.13.2`.

Yeah because I want to reproduce the error. Fresh install will install 6.13.2 which does not cause this error.

The reason I raised this issue is that for some existing application that bumps the dependency, such `pino` dependency prerequisite for `fastify` won't bump the existing `pino` dependency, which could cause this naughty error.

But I guess if this is kind of a rare case, then we can just wait for `pino@7`?

**Comment by jsumners** [comment]
This is not a Fastify issue. Fastify does not depend on any version of `pino-pretty`. Applications that do are responsible for paying attention to semver major release changes and acting accordingly.
