### ISSUE TITLE
Dependency checking fails for non-function type Request Decorators starting in version 3.21.6

### ISSUE THREAD

**Issue by meisly** [fastify/fastify#3517]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

3.21.6 and after

### Node.js version

11.10.0

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

Centos 6.10

### Description

Currently (in fastify versions after v3.21.5)  when a request decorator that is not a function is added it is no longer added to the request prototype directly but instead added to the props array.  However, the checkDependencies function does not check the props array.  This results in a situation where the "The decorator is missing dependency __" error is thrown even when the dependency is present and the hasRequestDecorator function returns true. 

### Steps to Reproduce

```
const fastify = require('fastify');
const app = fastify( fastifyOpts )

const decorator1 = {
  config: config,
  app: {},
}
const decorator2 = {
  stuff: stuff
}

app.decorate( 'decorator1', decorator1 )
app.decorateRequest( 'decorator1', decorator1 )

if ( app.hasDecorator( 'decorator1' ) && app.hasRequestDecorator( 'decorator1' ) ) {
  app.decorateRequest( 'decorator2', decorator2, 'decorator1'  )
}

```
This works in versions 3.21.5 and earlier but starting in v3.21.6 it results in a missing dependency error

### Expected Behavior

I expect no error

**Comment by climba03003** [comment]
I think updating the below line can resolve the issue
https://github.com/fastify/fastify/blob/aec2ac770036a34ce5a426037ef02070f07ca8ea/lib/decorate.js#L102

Would you like to send an Pull Request to address this issue? Remember to add an unit test.

**Comment by asaid-0** [comment]
I can reproduce the issue using this:

```javascript
const app = require('../fastify')({ logger: true })

app.decorateRequest('decorator1', { decorator1: 1 })

if (app.hasRequestDecorator('decorator1')) {
  app.decorateRequest('decorator2', { decorator2: 2 }, ['decorator1'])
}
```

The issue in `decorateRequest` and `decorateReply` as well and it's related to this change: #3337
https://github.com/fastify/fastify/blob/aec2ac770036a34ce5a426037ef02070f07ca8ea/lib/decorate.js#L53

we need to do the same idea as `checkRequestExistence` inside `checkDependencies` function as it calls `checkExistence` not  `checkRequestExistence`:
```javascript
if (name && hasKey(this[kRequest], name)) return true
```

I tried to implement some fixes but they break the tests
