### ISSUE TITLE
Upgrading from 3.18.0 to  3.18.1 triggers Typescript errors when registering plugins

### ISSUE THREAD

**Issue by actraiser** [fastify/fastify#3177]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure it has not already been reported

### Fastify version

3.18.1

### Node.js version

14.17

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

10.15.7

### Description

When upgrading from Fastify 3.18.0 to 3.18.1 plugins can not be registered anymore without Typescript-Errors. This was experienced with the plugins fastify-cors, fasitfy-cookie and fastify-jwt. Not sure if this applies to every plugin.

I use the following import syntax:

```
import fastify from 'fastify';
import * as fastifyCookie from 'fastify-cookie';
```

and then register the plugins like this into fastify:

````
const app = fastify({ logger: false });
app.register(fastifyCookie.default, {
  secret: process.env.COOKIE_SECRET_KEY,
});
````
In Fastify 3.18.0, this works fine. In Fastify 3.18.1 Typescript Errors are piling up, e.g. for fastify-cookie:

```
Property 'cookies' does not exist on type 'FastifyRequest<RouteGenericInterface, Server, IncomingMessage>'.
Property 'unsignCookie' does not exist on type 'FastifyInstance<Server, IncomingMessage, ServerResponse, FastifyLoggerInstance>'.
Property 'setCookie' does not exist on type 'FastifyReply<Server, IncomingMessage, ServerResponse, RouteGenericInterface, unknown>'.
```

I have not spotted updates in the release changelog of 3.8.1 that would explain this new behavior.  Maybe I do import/registering wrong to begin with but up to 3.8.0 it worked fine without Typescript errors.

Greets
-act

### Steps to Reproduce

See Description

### Expected Behavior

Import and Registering plugins work like in 3.18.0

**Comment by climba03003** [comment]
I can't reproduce the error you have. I use the following snippets for the reproduce the problem.
```ts
import Fastify from 'fastify'
import FastifyCookie from 'fastify-cookie'

const fastify = Fastify()

fastify.register(FastifyCookie)

fastify.get('/', function(request, reply) {
  request.cookies
  request.unsignCookie('foo')
  reply.setCookie('foo', 'bar')
})
```

You can see no warning or error from the IDE. Please ensure it is not the problem of IDE. Try to restart it to see if it help.
![image](https://user-images.githubusercontent.com/23028015/124390273-57195480-dd1d-11eb-9f7f-e027f97ff81a.png)

**Comment by actraiser** [comment]
Thank you for the quick response. Restarting the IDE did not resolve the issue. But thanks for confirming that importing and registering plugins should still work as usual. I will go check what else in my setup might cause the problem when going from 3.18.0 to 3.18.1. 

-act

**Comment by actraiser** [comment]
It turned out that the underlying problem was a faulty yarn workspaces setup. Thanks again.
