### ISSUE TITLE
Fastify 5.6.2+ breaks Docker + VSCode debug due to pino@10 transport worker

### ISSUE THREAD

**Issue by murillotlopes** [fastify/fastify#6493]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have searched existing issues to ensure the regression has not already been reported

### Last working version

5.6.1

### Stopped working in version

5.6.2

### Node.js version

22..22.0

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

Alpine 3.23.3 x86

## Description

After upgrading to **Fastify 5.6.2 or later**, applications may crash at startup when running in **Docker and debugging with VSCode**, even without any code changes.

This behavior was introduced indirectly by the dependency bump to **pino@10** in Fastify 5.6.2 and does **not occur in Fastify 5.6.1**, which still uses pino 9.x.

This is **not a Fastify bug per se**, but a breaking behavior affecting common development workflows.

---

## Environment

- **Fastify:** >= 5.6.2 (works correctly on 5.6.1)
- **Pino:** 10.x
- **Node.js:** v22.x
- **VSCode:** 1.108.2
- **Debugger:** VSCode Node debugger (attach / inspect-brk)
- **Runtime:** Docker container
- **OS:** Linux
- **Logger transport:** `pino-pretty`

---

## Scenario / Steps to reproduce

1. Run an application inside a **Docker container**.
2. Start Node with the debugger enabled, for example:

   ```bash
   node --inspect-brk=0.0.0.0:9229 ...
   ```

3. Attach to the process with the **VSCode Node debugger**.
4. Configure Fastify logging using a Pino transport (e.g. `pino-pretty`).
5. Start the app (or let it resume from `--inspect-brk`).

This setup is common for local development and debugging.

---

## Observed behavior

The process crashes during startup (before user code runs) with:

```text
Error: Cannot find module '/usr/share/code/resources/app/extensions/ms-vscode.js-debug/src/bootloader.js'

Require stack:
- internal/preload
```

And terminates with:

```text
Waiting for the debugger to disconnect...
```

---

## Expected behavior

When debugging inside Docker, enabling a Pino transport should not crash the application at startup.

---

## Root cause (analysis)

- Fastify 5.6.2 upgraded its dependency to `pino@10`.
- In Pino 10, transport runs in a worker thread.
- Worker threads inherit `process.execArgv`.
- When debugging with VSCode, Node is started with something like:

  ```text
  --require <VSCode debug bootloader>
  ```

- Inside Docker, the referenced VSCode bootloader path does not exist.
- The worker attempts to preload this file and crashes with `MODULE_NOT_FOUND`.
- The error occurs during Node’s preload phase and cannot be intercepted.

This behavior did not exist with Pino 9.x, which is why Fastify 5.6.1 works correctly.

---

## Impact

- Upgrading Fastify from 5.6.1 to 5.6.2+ can break local development.
- Users experience crashes without changing application code.
- A common workflow (Docker + VSCode debug) becomes unusable.
- The issue is non-obvious and difficult to diagnose.

---

## Related issue (upstream)

- Pino issue: https://github.com/pinojs/pino/issues/2389

---

## Suggested actions for Fastify

This likely does not require a direct code fix in Fastify, but the following would help users:

- Document this behavior in the release notes or migration guide.
- Warn users about Pino 10 transport behavior when debugging.
- Suggest mitigations, such as:
  - Downgrade / pin Pino to 9.x
  - Disable logger transport when debugging
  - Avoid transport in containerized debug environments

---

## Workarounds

- Downgrade Fastify to 5.6.1, or
- Pin Pino to 9.x, or
- Disable logger transport during debugging

All of these confirm the issue is introduced by the dependency upgrade.

---

## Final notes

- This is not a Fastify implementation bug.
- The issue is reported here for visibility and user guidance.
- The root cause and fix are being tracked upstream in Pino.

### Prerequisites
- Node.js **v22.x**
- VSCode **1.108.2**
- Docker / Docker Compose
- A Fastify app running inside a Docker container
- VSCode attaching to the containerized Node inspector (`--inspect-brk`)

---

### 1) Create a minimal Fastify app

`server.js` (or `server.ts`):

```js
import fastify from 'fastify'

const app = fastify({
  logger: {
    level: 'trace',
    transport: {
      target: 'pino-pretty',
      options: {
        colorize: true,
        translateTime: 'HH:MM:ss Z',
        ignore: 'pid,hostname'
      }
    }
  }
})

app.get('/health', async () => ({ ok: true }))

await app.listen({ host: '0.0.0.0', port: 3000 })
```

---

### 2) Use Fastify 5.6.2+ (regression) vs 5.6.1 (works)

`package.json`:

```json
{
  "type": "module",
  "scripts": {
    "dev:debug": "node --inspect-brk=0.0.0.0:9229 server.js"
  },
  "dependencies": {
    "fastify": "^5.6.2"
  }
}
```

Install deps:

```bash
npm install
```

Notes:

- With `fastify@5.6.1` the setup works as expected.
- With `fastify@>=5.6.2` it reproduces the crash (due to `pino@10` bump).

---

### 3) Run inside Docker

`Dockerfile`:

```dockerfile
FROM node:22-alpine

WORKDIR /app
COPY package*.json ./
RUN npm ci

COPY . .
EXPOSE 3000 9229
CMD ["npm", "run", "dev:debug"]
```

Build and run:

```bash
docker build -t fastify-debug-repro .
docker run --rm -p 3000:3000 -p 9229:9229 fastify-debug-repro
```

You should see Node listening for debugger on 0.0.0.0:9229.

### 4) Attach VSCode debugger

Create `.vscode/launch.json`:

```json
{
  "version": "0.2.0",
  "configurations": [
    {
      "type": "node",
      "request": "attach",
      "name": "Debug via Docker",
      "port": 9229,
      "restart": true,
      "protocol": "inspector",
      "address": "localhost",
      "localRoot": "${workspaceFolder}",
      "remoteRoot": "/app",
      "skipFiles": [
        "<node_internals>/**",
        "**/node_modules/**"
      ]
    }
  ]
}
```

Start the VSCode debug session (Attach to Docker).

---

### 5) Observe the crash (Fastify >= 5.6.2)

After attaching, the process crashes with:

```text
Error: Cannot find module
'/usr/share/code/resources/app/extensions/ms-vscode.js-debug/src/bootloader.js'

Require stack:
- internal/preload
```

Then:

```text
Waiting for the debugger to disconnect...
```

---

## Expected Result

Fastify should keep running after debugger attach, and /health should respond normally.

## Actual Result

Process crashes during Node preload when pino transport worker starts (`pino@10`).

## Notes / Confirmation

- Downgrading to `fastify@5.6.1` makes the exact same setup work.
- Disabling `logger.transport` also makes the setup work on `fastify@>=5.6.2`.
- Root cause is tracked upstream in Pino: https://github.com/pinojs/pino/issues/2389

**Comment by mcollina** [comment]
Thanks for reporting, I've opened a couple of PRs to handle this, both in Fastify and Pino.

**Comment by climba03003** [comment]
Issue is solved in upstream.
