### ISSUE TITLE
TypeScript issue while running Fastify TS code after upgrading to 4.9.1

### ISSUE THREAD

**Issue by rdzidziguri** [fastify/fastify#4354]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the regression has not already been reported

### Last working version

4.9.0

### Stopped working in version

4.9.1

### Node.js version

16

### Operating system

Windows

### Operating system version (i.e. 20.04, 11.3, 10)

11

### 💥 Regression Report

```
src/App.ts(13,11): error TS2322: Type 'FastifyInstance<RawServerDefault, IncomingMessage, ServerResponse<IncomingMessage>, FastifyBaseLogger<FastifyBaseLogger<any>>, FastifyTypeProviderDefault> & PromiseLike<...>' is not assignable to type 'FastifyInstance<RawServerDefault, IncomingMessage, ServerResponse<IncomingMessage>, DefaultFastifyLogger, FastifyTypeProviderDefault>'.
  Types of property 'log' are incompatible.
    Property 'setBindings' is missing in type 'FastifyBaseLogger<FastifyBaseLogger<any>>' but required in type 'DefaultFastifyLogger'.
```
Got the compilation error after upgrading to 4.9.1, but it should not be a breaking change. I expected this release to be backward compatible.
Here is the configuration of the logger;
```TypeScript
logger: {
            name: 'PICO',
            base: null,
            redact: {
                paths: ['systemId', 'timestamp'],
                remove: true
            }
        },
        disableRequestLogging: true
```

### Steps to Reproduce

Just create basic fastify instance, specify logger without above mentioned binding and run it through `ts-node`

### Expected Behavior

The app should run without specifying any setBindings if not needed.

**Comment by climba03003** [comment]
Interesting, the types do not pass down correctly.

**Comment by climba03003** [comment]
@BlackHole1 I am sorry, can you take a look on it?
If the it cannot be solves in a short time, I think we may revert https://github.com/fastify/fastify/pull/4346.

I can comes up a non-perfect solution, but is that OK for you?
```ts
export interface FastifyBaseLogger extends pino.BaseLogger, Partial<Omit<pino.Logger, 'child' | keyof pino.BaseLogger>> {
  child(bindings: Bindings, options?: ChildLoggerOptions): FastifyBaseLogger
}

export interface DefaultFastifyLogger extends FastifyBaseLogger {
  child(bindings: Bindings, options?: ChildLoggerOptions): DefaultFastifyLogger
}
```

You may need to add `?` before calling `setBindings?({})`

**Comment by BlackHole1** [comment]
@climba03003 I think we should revert #4346. Until we come up with a better solution, we should not make the code look as if it is normal.

**Comment by climba03003** [comment]
> @climba03003 I think we should revert #4346. Until we come up with a better solution, we should not make the code look as if it is normal. Because I'm worried that if we continue to fix it, it might cause other problems.

I believe if there would be a better solution, it will be inside next major.
You can use a workaround for declaration merging.
