### PR TITLE
Revert "fix(logger): lost setBindings type in FastifyBaseLogger"

### LINKED ISSUE #4354: TypeScript issue while running Fastify TS code after upgrading to 4.9.1
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the regression has not already been reported

### Last working version

4.9.0

### Stopped working in version

4.9.1

### Node.js version

16

### Operating system

Windows

### Operating system version (i.e. 20.04, 11.3, 10)

11

### 💥 Regression Report

```
src/App.ts(13,11): error TS2322: Type 'FastifyInstance<RawServerDefault, IncomingMessage, ServerResponse<IncomingMessage>, FastifyBaseLogger<FastifyBaseLogger<any>>, FastifyTypeProviderDefault> & PromiseLike<...>' is not assignable to type 'FastifyInstance<RawServerDefault, IncomingMessage, ServerResponse<IncomingMessage>, DefaultFastifyLogger, FastifyTypeProviderDefault>'.
  Types of property 'log' are incompatible.
    Property 'setBindings' is missing in type 'FastifyBaseLogger<FastifyBaseLogger<any>>' but required in type 'DefaultFastifyLogger'.
```
Got the compilation error after upgrading to 4.9.1, but it should not be a breaking change. I expected this release to be backward compatible.
Here is the configuration of the logger;
```TypeScript
logger: {
            name: 'PICO',
            base: null,
            redact: {
                paths: ['systemId', 'timestamp'],
                remove: true
            }
        },
        disableRequestLogging: true
```

### Steps to Reproduce

Just create basic fastify instance, specify logger without above mentioned binding and run it through `ts-node`

### Expected Behavior

The app should run without specifying any setBindings if not needed.

### PR DESCRIPTION
**Pull request by climba03003**
Reverts fastify/fastify#4346

Fixes #4354 https://github.com/fastify/fastify-websocket/issues/226

Pretty sad that it is too breaking for now.

### CODE REVIEW

**Review by BlackHole1 — APPROVED** [review]

**Review by Eomm — APPROVED** [review]
Does it reopen https://github.com/fastify/fastify/issues/4344 ?

**Comment by BlackHole1** [comment]
> Does it reopen #4344 ?

Yes. It need to reopen.

**Comment by climba03003** [comment]
I am thinking of moving one step forward and revert https://github.com/fastify/fastify/pull/4150 all together.
#4150 itself is a breaking changes.

cc @fastify/typescript

**Review by Uzlopak — APPROVED** [review]
